name: Build-All-Platforms

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os: [macos-latest, macos-13, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Build Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.7'
          spec: 'app/MotionFrame.py'
          requirements: 'app/requirements.txt'
          exe_path: './build'
          options: --name "Motion Frame", --windowed, --add-data=app/translation:translation,

      - uses: skymatic/code-sign-action@v3.0.0
        if: matrix.os == 'windows-latest'
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.PASSWORD }}'
          certificatesha1: '${{ secrets.CERTHASH }}'
          description: 'MotionFrame'
          timestampUrl: 'http://timestamp.digicert.com'
          folder: 'build'
          recursive: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} Build
          path: |
            build
          include-hidden-files: true
