name: Build-All-Platforms

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os: [macos-latest, macos-13, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app/MotionFrame.py
          standalone: true
          onefile: true
          enable-plugins: pyside6
          product-name: MotionFrame
          product-version: '1.0'
          file-version: '1.0'
          company-name: 'aki-null.net'
          copyright: 'aki-null'
          trademarks: 'aki-null'
          file-description: 'MotionFrame is a tool to analyze flipbook texture and generate motion vector atlas texture'
          include-data-dir: 'app/translation=translation'
          macos-create-app-bundle: true
          macos-app-name: MotionFrame
          macos-signed-app-name: com.akinull.motionframe
          windows-console-mode: disable

      - uses: skymatic/code-sign-action@v3.0.0
        if: matrix.os == 'windows-latest'
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.PASSWORD }}'
          certificatesha1: '${{ secrets.CERTHASH }}'
          description: 'MotionFrame'
          timestampUrl: 'http://timestamp.digicert.com'
          folder: 'build'
          recursive: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} Build
          path: |
            build/*.exe
            build/*.app/**/*
          include-hidden-files: true
